# Copyright (C) 2023  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Which Docker image shall be used on the GitLab runner?
image: docker:19.03.3

# Details about how to connect to the Docker service to run this build.
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:19.03.3-dind

stages:
  - build       # stage is executed for each push (irrespective of branch), not release
  - deploy      # stage is executed -
                  # if new release,
                  # if previous process (build) succeeded,
                  # release is versioned correctly in the form vX.X.X

# This section describes what shall be done to build and test the project.
build:
  tags:
    - docker-build
  stage: build
  rules:
    - exists:
        - Dockerfile
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
  script:
    - cd src
    - docker build -f Dockerfile .

# This section describes what shall be done to deploy artefacts from the project.
release:
# Display information before we start the build.
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
      when: always
    - if: $CI_COMMIT_TAG
  tags:
    - docker-build
  needs: ["build"]
  stage: deploy
  before_script:
    - CI_COMMIT_TAG=$CI_COMMIT_TAG ./regex-check.sh
  script:
    - cd src
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"
